on: push
name: "CI"
jobs:
  parserImages:
    name: "Build / Parsers"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker/build-push-action@v1
        name: "Build & Push Parser SDK"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: fuhrmeistery/parser-sdk-nodejs
          path: ./parser-sdk/nodejs/
          tag_with_ref: true
          tag_with_sha: true
